Compatibylity with Symfony 6.2
imatic/testing pull request #8
Opened 2023-03-23 13:18 UTC by jarogit

2023-03-23 15:35 UTC, ldfk requested changes

2023-03-23 15:35 UTC, ldfk commented on composer.json
> +        "symfony/framework-bundle": "^6.2",
pokud k tomu nejsou zadne duvody, tak by symfony bundly mely podporovat vsechny podporovane verze [symfony](https://symfony.com/releases). 

ty jsi timhle omezil podporu pouze na verzi 6.2 a vyssi. tzn mela by vzniknout nova major verze, ale kdyz se podivam na vsechny zmeny co jsi provedl tak k tomu nevidim duvod. muze byt tedy zachovana podpora `"symfony/framework-bundle": "^4.4|^5.4^6.2"`?

stejne tak neni uplne nutnost rusit zatim podporu pro php 7.4, aspon z tvych zmen k tomu taky nevidim duvod.

2023-03-23 15:35 UTC, ldfk commented on composer.json
> +        "phpunit/phpunit": "^10.0",
proc jsi presunul do dev zavislosti? bundle slouzi ke psani phpunit testu, proto toto bylo nastaveno jako prima zavislost.

a je potreba prechazet na vyssi verzi phpunit, nebo muze zustat zachovano `"phpunit/phpunit": "^9.5|^10.0"`?

2023-03-23 16:05 UTC, jarogit commented on composer.json
> +        "phpunit/phpunit": "^10.0",
ano, může zůstat, obnovena verze `phpunit/phpunit:9.5`

2023-03-27 09:57 UTC, jarogit commented on composer.json
> +        "symfony/framework-bundle": "^6.2",
opraveno.

2023-03-27 14:01 UTC, ldfk approved these changes

2023-03-27 14:01 UTC, merged